/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeboldalKeszitesRouteImport } from './routes/weboldal-keszites'
import { Route as VelemenyekRouteImport } from './routes/velemenyek'
import { Route as SzabalyzatRouteImport } from './routes/szabalyzat'
import { Route as ReferenciakRouteImport } from './routes/referenciak'
import { Route as ProgramozasRouteImport } from './routes/programozas'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R3dNyomtatasRouteImport } from './routes/3d-nyomtatas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicNotifyReviewRouteImport } from './routes/api/public/notify-review'

const WeboldalKeszitesRoute = WeboldalKeszitesRouteImport.update({
  id: '/weboldal-keszites',
  path: '/weboldal-keszites',
  getParentRoute: () => rootRouteImport,
} as any)
const VelemenyekRoute = VelemenyekRouteImport.update({
  id: '/velemenyek',
  path: '/velemenyek',
  getParentRoute: () => rootRouteImport,
} as any)
const SzabalyzatRoute = SzabalyzatRouteImport.update({
  id: '/szabalyzat',
  path: '/szabalyzat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciakRoute = ReferenciakRouteImport.update({
  id: '/referenciak',
  path: '/referenciak',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramozasRoute = ProgramozasRouteImport.update({
  id: '/programozas',
  path: '/programozas',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dNyomtatasRoute = R3dNyomtatasRouteImport.update({
  id: '/3d-nyomtatas',
  path: '/3d-nyomtatas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyReviewRoute = ApiPublicNotifyReviewRouteImport.update({
  id: '/api/public/notify-review',
  path: '/api/public/notify-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-nyomtatas': typeof R3dNyomtatasRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/programozas': typeof ProgramozasRoute
  '/referenciak': typeof ReferenciakRoute
  '/szabalyzat': typeof SzabalyzatRoute
  '/velemenyek': typeof VelemenyekRoute
  '/weboldal-keszites': typeof WeboldalKeszitesRoute
  '/api/public/notify-review': typeof ApiPublicNotifyReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-nyomtatas': typeof R3dNyomtatasRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/programozas': typeof ProgramozasRoute
  '/referenciak': typeof ReferenciakRoute
  '/szabalyzat': typeof SzabalyzatRoute
  '/velemenyek': typeof VelemenyekRoute
  '/weboldal-keszites': typeof WeboldalKeszitesRoute
  '/api/public/notify-review': typeof ApiPublicNotifyReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-nyomtatas': typeof R3dNyomtatasRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/programozas': typeof ProgramozasRoute
  '/referenciak': typeof ReferenciakRoute
  '/szabalyzat': typeof SzabalyzatRoute
  '/velemenyek': typeof VelemenyekRoute
  '/weboldal-keszites': typeof WeboldalKeszitesRoute
  '/api/public/notify-review': typeof ApiPublicNotifyReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-nyomtatas'
    | '/admin'
    | '/auth'
    | '/kapcsolat'
    | '/programozas'
    | '/referenciak'
    | '/szabalyzat'
    | '/velemenyek'
    | '/weboldal-keszites'
    | '/api/public/notify-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-nyomtatas'
    | '/admin'
    | '/auth'
    | '/kapcsolat'
    | '/programozas'
    | '/referenciak'
    | '/szabalyzat'
    | '/velemenyek'
    | '/weboldal-keszites'
    | '/api/public/notify-review'
  id:
    | '__root__'
    | '/'
    | '/3d-nyomtatas'
    | '/admin'
    | '/auth'
    | '/kapcsolat'
    | '/programozas'
    | '/referenciak'
    | '/szabalyzat'
    | '/velemenyek'
    | '/weboldal-keszites'
    | '/api/public/notify-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dNyomtatasRoute: typeof R3dNyomtatasRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  KapcsolatRoute: typeof KapcsolatRoute
  ProgramozasRoute: typeof ProgramozasRoute
  ReferenciakRoute: typeof ReferenciakRoute
  SzabalyzatRoute: typeof SzabalyzatRoute
  VelemenyekRoute: typeof VelemenyekRoute
  WeboldalKeszitesRoute: typeof WeboldalKeszitesRoute
  ApiPublicNotifyReviewRoute: typeof ApiPublicNotifyReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weboldal-keszites': {
      id: '/weboldal-keszites'
      path: '/weboldal-keszites'
      fullPath: '/weboldal-keszites'
      preLoaderRoute: typeof WeboldalKeszitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/velemenyek': {
      id: '/velemenyek'
      path: '/velemenyek'
      fullPath: '/velemenyek'
      preLoaderRoute: typeof VelemenyekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szabalyzat': {
      id: '/szabalyzat'
      path: '/szabalyzat'
      fullPath: '/szabalyzat'
      preLoaderRoute: typeof SzabalyzatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenciak': {
      id: '/referenciak'
      path: '/referenciak'
      fullPath: '/referenciak'
      preLoaderRoute: typeof ReferenciakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programozas': {
      id: '/programozas'
      path: '/programozas'
      fullPath: '/programozas'
      preLoaderRoute: typeof ProgramozasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-nyomtatas': {
      id: '/3d-nyomtatas'
      path: '/3d-nyomtatas'
      fullPath: '/3d-nyomtatas'
      preLoaderRoute: typeof R3dNyomtatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-review': {
      id: '/api/public/notify-review'
      path: '/api/public/notify-review'
      fullPath: '/api/public/notify-review'
      preLoaderRoute: typeof ApiPublicNotifyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dNyomtatasRoute: R3dNyomtatasRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  KapcsolatRoute: KapcsolatRoute,
  ProgramozasRoute: ProgramozasRoute,
  ReferenciakRoute: ReferenciakRoute,
  SzabalyzatRoute: SzabalyzatRoute,
  VelemenyekRoute: VelemenyekRoute,
  WeboldalKeszitesRoute: WeboldalKeszitesRoute,
  ApiPublicNotifyReviewRoute: ApiPublicNotifyReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
